<?php

namespace tankist\UploaderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VimeoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VimeoRepository extends EntityRepository
{
}